swagger: '2.0'
info:
  title: Resource Inventory Management
  description: todo
  version: 4.0.1
host: serverRoot
basePath: /tbd/v1
schemes:
  - https
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
tags:
  - name: Mapping BNG Port - LineIDs
paths:
  /bngPortForLineId:
    get:
      tags:
        - "Mapping BNG Port - LineIDs"
      summary: "Retrieval of BNG Port Identifier"
      description: "Retrieval of BNG Port Identifier for a given LineId in the context of Wholebuy "
      operationId: "bngPortForLineId"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: lineId
          in: query
          description: LineID of a Wholebuy AccessLine 
          required: true
          type: string
      responses:
        '200':
          description: Mapping result
          schema:
            type: object
            properties:
               endsz:
                  type: string
                  description: endsz of BNG device
               portName:
                  type: string
                  description: name of BNG port
            required:
              - endsz
              - portName
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
  /lineIdsForBngPort:
    get:
      tags:
        - "Mapping BNG Port - LineIDs"
      summary: "Retrieval of assigned lineIDs for a whole BNG device or a single BNG Port"
      description: "Retrieval of all wholebuy lineIDs for a single BNG Port or the whole BNG device if the portName parameter is missing."
      operationId: "lineIdsForBngPort"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: endsz
          in: query
          description: endsz of BNG device 
          required: true
          type: string
        - name: portName
          in: query
          description: portName of BNG port 
          required: false
          type: string
      responses:
        '200':
          description: Mapping result
          schema:
            type: object
            properties:
               lineIdList:
                  type: array
                  minItems: 0
                  items:
                    type: string
                    description: LineID
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '405':
          description: Method Not allowed
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    description: >-
      Used when an API throws an Error, typically with a HTTP error
      response-code (3xx, 4xx, 5xx)
    type: object
    required:
      - code
      - reason
    properties:
      code:
        type: string
        description: 'Application relevant detail, defined in the API or a common list.'
      reason:
        type: string
        description: >-
          Explanation of the reason for the error which can be shown to a client
          user.
      message:
        type: string
        description: >-
          More details and corrective actions related to the error which can be
          shown to a client user.
      status:
        type: string
        description: HTTP Error code extension
      referenceError:
        type: string
        format: uri
        description: URI of documentation describing the error.
      '@baseType':
        type: string
        description: 'When sub-classing, this defines the super-class.'
      '@schemaLocation':
        type: string
        format: uri
        description: >-
          A URI to a JSON-Schema file that defines additional attributes and
          relationships
      '@type':
        type: string
        description: 'When sub-classing, this defines the sub-class entity name.'
